name: Go

on:
  push:
    branches:
      - master
      - 'feature/**'
    tags:
      - '*'

jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.26

      - name: Setup gotestsum
        uses: autero1/action-gotestsum@v0.1.0
        with:
          gotestsum_version: 0.4.1
      - name: Interact with gotestsum
        run: gotestsum --format short-verbose

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Upload terrafmt for docker build
        uses: actions/upload-artifact@v1
        with:
          name: docker-binary
          path: aws_ecr_proxy


  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - name: Download build artifact
        uses: actions/download-artifact@v1
        with:
          name: docker-binary

      - name: Move binary
        run: |
          mv docker-binary/aws_ecr_proxy aws_ecr_proxy
          chmod 755 aws_ecr_proxy

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build :latest
        run: |
          docker build -t terrycain/aws_ecr_proxy:latest .
          docker tag terrycain/aws_ecr_proxy:latest terrycain/aws_ecr_proxy:${{ steps.get_version.outputs.version }}
      - name: Push to docker hub :latest
        uses: actions-hub/docker@master
        with:
          args: push terrycain/aws_ecr_proxy:latest

      - name: Push to docker hub :${{ steps.get_version.outputs.version }}
        uses: actions-hub/docker@master
        with:
          args: push terrycain/aws_ecr_proxy:${{ steps.get_version.outputs.version }}
